---
# tasks file for conan-exiles-ansible-role
- name: Upgrade system
  become: 'True'
  apt:
    upgrade: 'True'

- name: Install dependencies
  become: 'True'
  package:
    name: "{{ item }}"
    state: present
    update_cache: 'True'
    autoremove: 'True'
    install_recommends: 'True'
  with_items:
    - python3-software-properties
    - curl
    - screen
    - ffmpeg
    - wine-stable
    - xvfb
    - git
    - wget
    - mc
    - joe
    - lib32gcc1
    #- wine32

- name: Create Steam user
  become: 'True'
  user:
    name: "{{ steam_user }}"
    system: 'True'

- name: Create game installation folder
  become: 'True'
  file:
    path: "{{ game_installation_folder }}"
    owner: "{{ steam_user }}"
    group: "{{ steam_user }}"
    state: directory

- name: Create SteamCMD installation script folder
  become: 'True'
  file:
    path: "{{ steamcmd_installation_folder }}"
    owner: "{{ steam_user }}"
    group: "{{ steam_user }}"
    state: directory

- name: Unarchive a file with extra options
  become: 'True'
  unarchive:
    src: "{{ steamcmd_download_link }}"
    dest: /usr/local/bin
    owner: "{{ steam_user }}"
    group: "{{ steam_user }}"
    mode: u=rwx,g=rx,o=rx
    remote_src: 'True'
  args:
    creates: /usr/local/bin/steamcmd.sh

- name: Prepare server installation script
  become: 'True'
  become_user: "{{ steam_user }}"
  template:
    src: install_conan_server.txt
    dest: "{{ steamcmd_installation_folder }}/install_conan_server.txt"
    owner: "{{ steam_user }}"
    group: "{{ steam_user }}"

- name: Install SteamCMD
  become: 'True'
  become_user: "{{ steam_user }}"
  command: "{{ steamcmd_install_command }}"
  args:
    creates: /usr/local/steam-services/conan/conan_exiles/ConanSandboxServer.exe
